SPR_TBL                     EQU $C0
SPR_TBL_SIZE                EQU (40 * 4)
SECTION "shadow_oam", WRAM0[SPR_TBL << 8]
SHADOW_OAM:
    ds SPR_TBL_SIZE

STACK_POINTER               EQU $E000
STACK_POINTER_MAX_SIZE      EQU $02 * 40

SECTION "stack", WRAMX[(STACK_POINTER - STACK_POINTER_MAX_SIZE)], BANK[1]
STACK:
    ds STACK_POINTER_MAX_SIZE

SECTION "common_ram", WRAM0[(SPR_TBL << 8) + SPR_TBL_SIZE]
GAMEBOY_STATUS:
    ds $01
GAMEBOY_STATUS_VBLANK       EQU %00000001
